spring:
  retry:
    max-attempts: ${YSQL_RETRY_MAX_ATTEMPTS:5}
    backoff-initial-interval: ${YSQL_BACKOFF_INIT_INTERVAL_MS:2}
    backoff-multiplier: ${YSQL_BACKOFF_MULTIPLIER_MS:8}
    backoff-max-interval: ${YSQL_BACKOFF_MAX_INTERVAL_MS:3000}
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME:com.yugabyte.Driver}
    url: ${DATASOURCE_URL:jdbc:yugabytedb://localhost:5433/yugabyte?currentSchema=yb_device_us&load-balance=true}
    username: ${DATASOURCE_USERNAME:yugabyte}
    password: ${DATASOURCE_PASSWORD:}
    hikari:
      maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE:10}
      minimum-idle: ${HIKARI_MINIMUM_IDLE:10}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT:0}
      max-lifetime: ${HIKARI_MAX_LIFETIME:14400000} # 4h
      keepalive-time: ${HIKARI_KEEPALIVE_TIME:900000} # 15m
      transaction-isolation: ${HIKARI_TRANSACTION_ISOLATION:TRANSACTION_READ_COMMITTED}
      connection-init-sql: ${HIKARI_CONNECTION_INIT_SQL:}
      data-source-properties:
        socketTimeout: ${YSQL_SOCKET_TIMEOUT:15} # default 0s
        connectTimeout: ${YSQL_CONNECT_TIMEOUT:10} # default 10s
        loginTimeout: ${YSQL_LOGIN_TIMEOUT:0} # default 0s means infinity
        options: ${YSQL_OPTIONS:-c statement_timeout=8s}
        prepareThreshold: ${YSQL_PREPARE_THRESHOLD:1}
  flyway:
    default-schema: ${DATABASE_SCHEMA:yb_device_us}
    user: ${FLYWAY_USERNAME:yugabyte}
    password: ${FLYWAY_PASSWORD:}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:false}
    mixed: ${FLYWAY_MIXED:true} # requires if you explicitly state "concurrently" which is non-transactional
    placeholders:
      env: qa
      ybIndexMode: nonconcurrently
      deviceCount: 5000
      mediaPerDeviceCount: 60

## Added for K8s environments
management:
  endpoint:
    health.probes.enabled: true
  health.probes:
    livenessstate.enabled: true
    readinessstate.enabled: true
  endpoints:
    web:
      exposure:
        include: health,prometheus

logging.level:
  com.zaxxer.hikari: ${HIKARI_LOG_LEVEL:TRACE}
  com.zaxxer.hikari.HikariConfig: ${HIKARI_CONFIG_LOG_LEVEL:DEBUG}
  com.yugabyte: ${YB_LOG_LEVEL:INFO}
  com.yugabyte.Driver: ${YB_DRIVER_LOG_LEVEL:INFO} # use DEBUG for connection info
  org.springframework.jdbc.core.JdbcTemplate: ${SPRING_JDBC_TEMPLATE_LOG:TRACE}
  org.springframework.retry.support.RetryTemplate: ${SPRING_RETRY_LOG:DEBUG}