apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-cm
data:
  locustfile.py: |
    from locust import HttpUser, task, between, tag
    import random
    import json

    class LoadSimulator(HttpUser):
        #wait_time = between(0.5, 1)
        json_headers = {'Content-Type': 'application/json', 'Accept': 'application/json'}    
        
        @task
        @tag('deviceTracker')
        def patch_device_tracker3(self):
            batch_size = 100
            self.client.post(f"/api/tracker/batch/{batch_size}")
